version: "3.9"
   
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgresqldb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgresqldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345