version: "3.9"
   
services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

  redisdb:
    image: redis
    ports:
      - 6379:6379
      
